BATCH_SIZE: 96
HEIGHT: 500
STRIDE: 500
WIDTH: 500
add_chm: 0
add_input2: 0
add_output_names: null
add_outputs: 0
add_seg: 0
augmentation_prob: 0.5
band_select: 1
beta1: 0.5
beta2: 0.999
chm_pred: 0
chm_resample: 1
dropoutchm: 10
imageNetnorm: 1
img_ch: 3
input2_name: ''
input_chm_dir: null
input_chm_pref: CHM
input_image_dir: /mnt/nfs/Planet/PlanetScope/Mosaics/South_America/2019 #/mnt/nfs/users/Xiaoye/greenhouse/input/test #/mnt/nfs/Planet/PlanetScope/Mosaics/Africa/2019
input_image_pref: ps
input_image_type: .jp2
inputlength: 224
keep_all_features: 0
lr: 0.0005
lr_decay_frequency: 60
lr_decay_rate: 0.9
meanstdnorm: 0
min_lr: 1.0e-05
mode: inference
model_path: /mnt/super/greenhouse/saved_models/classification_20221018-1150-torchEfficientnetb1-Epo200-patch_224-Loss_BCE-bands_RGB-_None/bestF1.pkl #/mnt/super/greenhouse/classification_20221004-0832-torchEfficientnetb0-Epo200-patch_224-Loss_BCE-bands_RGB-_None/bestF1.pkl
model_type: torchEfficientnetb1_dense
new_bands:
- 0
- 1
- 2
nnlevel: 4
num_epochs: 400
num_workers: 1
operator: REPLACE
output_act_suffix: gh_activation
output_activation: 0
output_ch: 1
output_dir: /mnt/nfs/users/Xiaoye/greenhouse/planet_gh_classification_1km
output_dtype: uint8
output_image_type: .tif
output_suffix: _1km
pretrained: 1
refine_seg: 0
sum_output: 0
t: 3
task: classification
to_predict_filelist: '/mnt/super/greenhouse/south_america.txt'
upscale: 1
weightDecay: 0.1
