BATCH_SIZE: 32
HEIGHT: 200
STRIDE: 200
WIDTH: 200
add_chm: 0
add_input2: 0
add_ndvi: 0
add_output_names: null
add_outputs: 0
add_seg: 0
augmentation_prob: 0.5
band_select: 1
beta1: 0.5
beta2: 0.999
chm_pred: 0
chm_resample: 1
dropoutchm: 10
imageNetnorm: 1
img_ch: 3
input2_name: ''
input_chm_dir: null
input_chm_pref: CHM
input_image_dir: /mnt/nfs/users/Xiaoye/greenhouse/clip_1km/north_america/
input_rescale: 1
input_image_pref: 'Clip'
input_image_type: .tif
inputlength: 224
keep_all_features: 0
lr: 0.0005
lr_decay_frequency: 60
lr_decay_rate: 0.9
meanstdnorm: 0
min_lr: 1.0e-05
mode: pred
model_path: /mnt/super/greenhouse/saved_models/classification_20221018-1150-torchEfficientnetb1-Epo200-patch_224-Loss_BCE-bands_RGB-_None/bestF1.pkl #/mnt/super/greenhouse/classification_20221004-0832-torchEfficientnetb0-Epo200-patch_224-Loss_BCE-bands_RGB-_None/bestF1.pkl
model_type: torchEfficientnetb1_dense
new_bands:
- 0
- 1
- 2
nnlevel: 4
num_epochs: 400
num_workers: 1
onlyRGB: 1
operator: REPLACE
output_act_suffix: AGB_activation
output_activation: 0
output_ch: 1
output_dir: /mnt/nfs/users/Xiaoye/greenhouse/clip_1km/
output_dtype: float32
output_image_type: .tif
output_table_type: .csv
output_suffix: north_america
pretrained: 1
refine_seg: 0
rgb2gray: 0
sum_output: 0
t: 3
task: classification
train_path: /mnt/nfs/users/Xiaoye/greenhouse/clip_1km/north_america/
upscale: 1
use_color: 1
weightDecay: 0.1
